### PR TITLE
Add cumsum and cumprod methods

### PR DESCRIPTION
**Pull request by jebej**
I didn't add documentation, since these are already documented by Julia base. It also seems that `@inline` is not necessary.

### CODE REVIEW

**Comment by Jutho** [comment]
Code and tests look good. For the docs, they are produced with documenter so adding them manually to `README.md` is not a good idea, as this will be overwritten when Documenter is ran the next time.  Just add your one-line description to the source file and add the name of these two methods in `docs/src/index.md`.

**Comment by jebej** [comment]
Huh, I did not know Documenter did `READMEs`. I made the change.

**Comment by Jutho** [comment]
Thanks. I also don't know Documenter to well, and maybe I am misusing it. I just use the file generated by Documenter in docs as a README. I don't know if I can have this done automatically on Github, so for now, your changes won't show up in the actual `README.md` until you or I run the `make.jl` file in `docs/` and then copy the output back to `README.md`.

**Comment by jebej** [comment]
Ah I see. You need to add a `deploydocs` statement to `make.jl` to have Travis automatically deploy the documentation to github pages. It's relatively simple to set up: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

**Comment by Jutho** [comment]
I never noticed that with this PR, you imported `cumsum` and `cumprod` from Base. This is not in line with the philosophy of TupleTools, which does not overload Base and also does not export any methods. If you want to use methods from TupleTools, you have to be explicit, i.e.
```julia
... = TupleTools.cumsum((...,))
```
Otherwise, this is considered type piracy. So I will remove these import statements from the latest version.

**Pull request merged**
